ApplicationWeb/Models/EmloyeDropDown.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Models
{
    public class EmloyeDropDown
    {
        public SelectList Employes { get; set; }

        public int EmployeId { get; set; }


    }
}

ApplicationWeb/Models/OffreViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Models
{
    public class OffreViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Intitule { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Un salaire négatif ??")]
        public float Salaire { get; set; }

        [Required]
        public string Description { get; set; }

        public StatutViewModel Statut { get; set; }

        [Display(Name = "Statut")]
        public int StatutId { get; set; }

        public SelectList Statuts { get; set; }

        public string Responsable { get; set; }

    }
}

ApplicationWeb/Models/PostulationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Models
{
    public class PostulationViewModel
    {
        public int OffreId { get; set; }

        public OffreViewModel Offre { get; set; }

        public int EmployeId { get; set; }

        [Display(Name = "Date de postultation")]
        public DateTime Date { get; set; }

        [Display(Name = "Statut postultation")]
        public string Statut { get; set; }

        public SelectList Employes { get; set; }
        
    }
}

ApplicationWeb/Models/StatutViewModel.cs
namespace ApplicationWeb.Models
{
    public class StatutViewModel
    {
        public int Id { get; set; }

        public string Libelle { get; set; }
    }
}

ApplicationWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Offre");
        }
    }
}

ApplicationWeb/Controllers/OffreController.cs
using ApplicationWeb.Converter;
using ApplicationWeb.Models;
using BunsinessLayer;
using Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class OffreController : Controller
    {

        private BusinessManager businessManager = BusinessManager.Instance;

        public ActionResult Index()
        {

            List<Offre> offres = businessManager.GetAllOffres();

            List<OffreViewModel> offresViewModel = new List<OffreViewModel>();

            foreach(Offre offre in offres)
            {
                offresViewModel.Add(OffreViewModelConverter.ConvertOffreToOffreViewModel(offre));
            }

            return View(offresViewModel);
        }

        public ActionResult ModifierOffre(int id)
        {
            Offre offretoModify = businessManager.GetOffreById(id);

            OffreViewModel offreVmToModify = OffreViewModelConverter.ConvertOffreToOffreViewModel(offretoModify);

            List<Statut> statuts = businessManager.GetAllStatuts();
            offreVmToModify.Statuts = new SelectList(statuts, "Id", "Libelle");

            return View(offreVmToModify);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ModifierOffre(OffreViewModel offreVm)
        {
            if (ModelState.IsValid)
            {
                Offre offretoModify = OffreViewModelConverter.ConvertOffreViewModelToOffre(offreVm);
                Offre offreUpdated = businessManager.ModifierOffre(offretoModify);
                offreVm = OffreViewModelConverter.ConvertOffreToOffreViewModel(offreUpdated);
            }

            return View("DetailOffre", offreVm);
        }


        public ActionResult DetailOffre(int id)
        {
            Offre offre = businessManager.GetOffreById(id);
            return View(OffreViewModelConverter.ConvertOffreToOffreViewModel(offre));
        }


        public ActionResult SupprimerOffre(int id)
        {
            businessManager.SupprimerOffre(id);
            return RedirectToAction("Index");
        }

        public ActionResult AjouterOffre()
        {
            OffreViewModel vm = new OffreViewModel();

            List<Statut> statuts = businessManager.GetAllStatuts();
            vm.Statuts = new SelectList(statuts, "Id", "Libelle");

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjouterOffre(OffreViewModel offreVm)
        {
            if (ModelState.IsValid)
            {
                Offre offretoAdd = OffreViewModelConverter.ConvertOffreViewModelToOffre(offreVm);
                int idNouvelOffre = businessManager.AjouterOffre(offretoAdd);
                return RedirectToAction("DetailOffre", new { id = idNouvelOffre });
            }
            List<Statut> statuts = businessManager.GetAllStatuts();
            offreVm.Statuts = new SelectList(statuts, "Id", "Libelle");

            return View(offreVm); 
        }

        public ActionResult RechercherOffre(string search)
        {
            if (String.IsNullOrWhiteSpace(search))
            {
                RedirectToAction("Index");
            }

            List < Offre > offres = businessManager.RechercheByIntituleOrDescription(search);

            List<OffreViewModel> offresVm = new List<OffreViewModel>();

            foreach(Offre offre in offres)
            {
                offresVm.Add(OffreViewModelConverter.ConvertOffreToOffreViewModel(offre));
            }

            return View("Index", offresVm);
        }


    }
}

ApplicationWeb/Controllers/PostulationController.cs
using ApplicationWeb.Converter;
using ApplicationWeb.Models;
using BunsinessLayer;
using Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationWeb.Controllers
{
    public class PostulationController : Controller
    {

        private BusinessManager businessManager = BusinessManager.Instance;

        public ActionResult Index()
        {
         
            return View();
        }

        public ActionResult PostulerOffre(int offreId)
        {
            PostulationViewModel postulationViewModel = new PostulationViewModel();
            postulationViewModel.OffreId = offreId;

            List<Employe> employes = businessManager.GetAllEmploye();
            postulationViewModel.Employes = new SelectList(employes, "Id", "Identite");

            return View(postulationViewModel);
        }

        [HttpPost]
        public ActionResult PostulerOffre(PostulationViewModel vm)
        {
            if (ModelState.IsValid)
            {
                businessManager.Postuler(vm.OffreId, vm.EmployeId);
                return RedirectToAction("Index","Home");
            }

            return RedirectToAction("PostulerOffre", new { offreId = vm.OffreId });
        }

        public ActionResult MesPostulations()
        {
            EmloyeDropDown vm = new EmloyeDropDown();
            List<Employe> employes = businessManager.GetAllEmploye();
            vm.Employes = new SelectList(employes, "Id", "Identite");

            return View(vm);
        }

        public ActionResult AfficherPostulationsByEmploye(int employeId)
        {
            List<Postulation> postulations = businessManager.GetAlPostulationsByEmployeId(employeId);
            List<PostulationViewModel> listeVm = new List<PostulationViewModel>();
            foreach(Postulation p in postulations)
            {
                listeVm.Add(PostulationViewModelConverter.ConvertToViewModel(p));
            }
            return PartialView(listeVm);
        }
    }
}

ApplicationWeb/Views/Offre/AffichageModifierOffre.cshtml
@model ApplicationWeb.Models.OffreViewModel

@using (Html.BeginForm("ModifierOffre", "Offre"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OffreViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.StatutId)

        <div class="form-group">
            @Html.LabelFor(model => model.Intitule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Intitule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Intitule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Responsable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Responsable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Responsable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplicationWeb/Views/Offre/AjouterOffre.cshtml
@model ApplicationWeb.Models.OffreViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OffreViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Intitule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Intitule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Intitule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Statut", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.StatutId, Model.Statuts, "---Statut--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatutId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Responsable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Responsable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Responsable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index", "Offre", null, new { @class = "btn-primary btn" })

</div>

<script>

</script>

ApplicationWeb/Views/Offre/DetailOffre.cshtml
@model ApplicationWeb.Models.OffreViewModel

<div>
    <h4>OffreViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Intitule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Intitule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model =>model.Statut.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Responsable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Responsable)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "ModifierOffre", "Offre", new { id = Model.Id }, new { @class = "btn-primary btn" })
    @Html.ActionLink("Retour à la liste", "Index", "Offre", null, new { @class = "btn-primary btn" })
</p>

ApplicationWeb/Views/Offre/Index.cshtml
@model IEnumerable<ApplicationWeb.Models.OffreViewModel>

    <nav class="navbar navbar-light bg-light d-flex flex-row">
        @using (Html.BeginForm("RechercherOffre", "Offre", FormMethod.Get, new { @class = "form-inline d-flex" }))
        {
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        }
    </nav>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Intitule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salaire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Responsable)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        @Html.HiddenFor(modelItem => item.Id)

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Intitule)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salaire)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Statut.Libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Responsable)
            </td>
            <td>
                @Html.ActionLink("Modifier", "ModifierOffre", "Offre", new { id = item.Id }, new { @class = "btn-primary btn" })
                @Html.ActionLink("Detail", "DetailOffre", "Offre", new { id = item.Id }, new { @class = "btn-primary btn" }) 
                @Html.ActionLink("Postuler", "PostulerOffre", "Postulation", new { offreId = item.Id }, new { @class = "btn-primary btn" })
                @Html.ActionLink("Supprimer", "SupprimerOffre", "Offre", new { id = item.Id }, new { @class = "btn-primary btn" })
            </td>
        </tr>
    }

</table>

ApplicationWeb/Views/Offre/ModifierOffre.cshtml
@model ApplicationWeb.Models.OffreViewModel

@using (Html.BeginForm("ModifierOffre", "Offre"))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>OffreViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Intitule, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Intitule, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Intitule, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salaire, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salaire, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Salaire, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Statut", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.StatutId, Model.Statuts, "---Statut--", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StatutId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Responsable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Responsable, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Responsable, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index", "Offre", null, new { @class = "btn-primary btn" })
</div>

ApplicationWeb/Views/Offre/PostulerOffre.cshtml
@model ApplicationWeb.Models.PostulationViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PostulationViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("T'es qui chacal , ya pas d'authentif ici", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.EmployeId, Model.Employes, "---Employee--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Postuler" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ApplicationWeb/Views/Postulation/AfficherPostulationsByEmploye.cshtml
@model IEnumerable<ApplicationWeb.Models.PostulationViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Initule de l'offre")
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Offre.Intitule)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Date)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Statut)
    </td>
    <td>
        @Html.ActionLink("Voir l'offre", "DetailOffre", "Offre", new { id = item.OffreId }, new { @class = "btn-primary btn" })
    </td>
</tr>
}

</table>

ApplicationWeb/Views/Postulation/MesPostulations.cshtml
@model ApplicationWeb.Models.EmloyeDropDown

<div>
    <h4>Mes Posulations</h4>
    <hr />

        <div class="form-group">
            @Html.Label("T'es qui chacal , ya pas d'authentif ici", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.EmployeId, Model.Employes, "---Employee--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="liste">

        </div>
</div>

<script>

    function afficherPostulations(value) {
        if (value) {
            let listePostulationsURL = "@Url.Action("AfficherPostulationsByEmploye")";
            let data = {
                employeId: value
            };
            console.log("zeze");
            $.get(listePostulationsURL, data, function (result) {
                console.log("zeze");
                $("#liste").html(result);
            })
            console.log("zeze");
        }
        else {
            $("#liste").html("");
        }
    }

    $(document).ready(function () {

        let value = $("#EmployeId").children("option:selected").val();
        console.log(value);
        afficherPostulations(value);

        $("#EmployeId").on('change', function () {
            value = $(this).children("option:selected").val();
            afficherPostulations(value);
        });
    });
</script>

ApplicationWeb/Views/Postulation/PostulerOffre.cshtml
@model ApplicationWeb.Models.PostulationViewModel

@using (Html.BeginForm("PostulerOffre", "Postulation")) 
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.OffreId)


    <div class="form-horizontal">
        <h4>PostulationViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("T'es qui chacal , ya pas d'authentif ici", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.EmployeId, Model.Employes, "---Employee--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Postuler" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index", "Offre", null, new { @class = "btn-primary btn" })
</div>

ApplicationWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestion d'offres</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body style="padding:unset">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            @Html.ActionLink("Accueil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Offres", "Index", "Home", new { area = "" },new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Mes postulations", "MesPostulations", "Postulation", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Actions
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="Actions">
                            <li>
                                @Html.ActionLink("Ajouter Offre", "AjouterOffre", "Offre", new { area = "" }, new { @class ="dropdown-item" })
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Gestion d'offres</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")

    @*  *@
    @RenderSection("scripts", required: false)
</body>
</html>